     pipeline {
        agent none
        stages {
         
          stage("build & sonarqube") {
            agent any
            steps {
              withSonarQubeEnv('sq1') {
                sh 'mvn clean package sonar:sonar'
              }
            }
          }
        }
      }
