     pipeline {
        agent any
           tools {
        maven 'jenkins-maven'
    }

        stages {
             stage('Git Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/sonar']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ZudaPradana/IoTLokomotive']])
                bat 'mvn clean install'
                echo 'Git Checkout Completed'
            }
        }
         
          stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    bat 'mvn clean package'
                    bat ''' mvn clean verify sonar:sonar -Dsonar.projectKey=sonar-analysis -Dsonar.projectName='sonar-analysis' -Dsonar.host.url=http://localhost:9000 '''
                    echo 'SonarQube Analysis Completed'
                }
            }
        }
             stage("Quality Gate") {
            steps {
                waitForQualityGate abortPipeline: true
                echo 'Quality Gate Completed'
            }
        }
        }
      }
